name: Check Shell Script Formatting ğŸ¨

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  shfmt-check:
    name: Check Formatting (shfmt) âœ¨
    runs-on: ubuntu-latest

    steps:
      - name: Check out code ğŸ›’
        uses: actions/checkout@v4

      - name: Run shfmt Format Check ğŸ§
        run: |
          echo " "
          echo "ğŸ¨ Running 'shfmt -i 2 -ci -sr -d' on ./Scripts ..."
          echo "-------------------------------------------------------------"
          docker pull mvdan/shfmt:latest-alpine
          docker run --rm -v "$(pwd):/mnt" -w /mnt mvdan/shfmt:latest-alpine -i 2 -ci -sr -d ./Scripts
          echo "-------------------------------------------------------------"
          echo "âœ… Formatting check complete! (Will fail if diffs were found)"
